### ISSUE TITLE
Server shows version 2.3.7 although image contains version 2.3.8

### ISSUE THREAD

**Issue by mtibke** [uroni/urbackup-server-docker-old#6]
Hi,

I have noticed that my server is informing me about an update to version 2.3.8 (current version shown as 2.3.7). I have therefore pulled the latest image again from DockerHub but the admin page still shows version 2.3.7 in the lower right corner.

Am I missing a step here?

Regards,
Martin

**Comment by Akruidenberg** [comment]
I' ve got this massage also. Which version is installed?

**Comment by mtibke** [comment]
Hi! I still have version 2.3.7 and it still doesn't update to v2.3.8.

**Comment by uroni** [comment]
So I downloaded the image with "docker save" and the binary says its version is 2.2.7.2131!!!
While the web interface is at version 2.3.7...

Idk how this is happening. Docker hub shows the image last being build 11 hours ago.

**Comment by uroni** [comment]
Hmm, must be some weird cache thing going on (docker save doesn't even have a --no-cache option :(). When I setup docker on a fresh instance versions match up and are up-to-date at 2.3.8. Maybe you are having the same problem?

**Comment by mtibke** [comment]
Thank you for checking this. I'm not sure that the issue comes from the image because I had rebuild it locally with the same configuration before and had the same issue. What I have changed now is to use a specific new volume name that stores the content of the path /usr/share/urbackup.

i.e. I changed
 -v urbackup_share:/usr/share/urbackup
tp
 -v urbackup_share_v238:/usr/share/urbackup

and after restarting the container with this setting the page shows the latestes version v2.3.8.
Does somebody now what is in this folder and why we need a specific volume for it?

Thanks

**Comment by uroni** [comment]
Thanks, I see. The idea was that by exporting it the web interface, the files in "/usr/share/urbackup/www" can be used in e.g. a apache2 container to serve the web interface.
But as you noticed, it'll cause the web interface files in "/usr/share/urbackup" not to update on rebuild. So now I have removed this volume export "/usr/share/urbackup". Should be updated within 24h.

**Comment by mtibke** [comment]
Thank you. I've tested it a few minutes ago with the rebuild image and without the volume mount for /usr/share/urbackup and everything looks fine.
